// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"github.com/google/wire"
	"net/http"
	"url-shortener/internal/app"
	"url-shortener/internal/config"
	"url-shortener/internal/service/url"
	"url-shortener/internal/ssoclient"
	"url-shortener/internal/storage/postgres"
	"url-shortener/internal/storage/redis"
	"url-shortener/internal/transport/http"
	"url-shortener/internal/transport/http/handlers"
	"url-shortener/pkg/random"
)

// Injectors from wire.go:

func InitializeRouter(cfg *config.Config) (http.Handler, func(), error) {
	logger := provideLogger(cfg)
	string2 := provideDatabaseURL(cfg)
	postgresRepo, cleanup, err := postgres.InitPostgres(logger, string2)
	if err != nil {
		return nil, nil, err
	}
	client, cleanup2, err := provideRedis(cfg, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	duration := provideCacheTTL(cfg)
	cache := redis.New(logger, postgresRepo, client, duration)
	generator := provideAliasGenerator(cfg)
	serviceConfig := provideServiceConfig(cfg)
	serviceService, err := service.New(logger, cache, generator, serviceConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	validate, err := provideValidator()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	handler := handlers.New(logger, serviceService, validate)
	options := provideSSOClientOptions(cfg)
	ssoclientClient, cleanup3, err := provideSSOClient(options)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	authHandler := handlers.NewAuth(logger, ssoclientClient)
	verifier, err := provideAuthVerifier(cfg)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	httpHandler := httptransport.NewRouter(logger, handler, authHandler, verifier, postgresRepo, client)
	return httpHandler, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// InitializeApp собирает DI-контейнер приложения
func InitializeApp(cfg *config.Config) (*app.App, func(), error) {
	logger := provideLogger(cfg)
	string2 := provideDatabaseURL(cfg)
	postgresRepo, cleanup, err := postgres.InitPostgres(logger, string2)
	if err != nil {
		return nil, nil, err
	}
	client, cleanup2, err := provideRedis(cfg, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	duration := provideCacheTTL(cfg)
	cache := redis.New(logger, postgresRepo, client, duration)
	generator := provideAliasGenerator(cfg)
	serviceConfig := provideServiceConfig(cfg)
	serviceService, err := service.New(logger, cache, generator, serviceConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	validate, err := provideValidator()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	handler := handlers.New(logger, serviceService, validate)
	options := provideSSOClientOptions(cfg)
	ssoclientClient, cleanup3, err := provideSSOClient(options)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	authHandler := handlers.NewAuth(logger, ssoclientClient)
	verifier, err := provideAuthVerifier(cfg)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	httpHandler := httptransport.NewRouter(logger, handler, authHandler, verifier, postgresRepo, client)
	server := httptransport.NewServer(cfg, httpHandler)
	appApp := app.New(logger, server)
	return appApp, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// StorageSet описывает зависимости уровня хранения данных
var StorageSet = wire.NewSet(

	provideDatabaseURL, postgres.InitPostgres, wire.Bind(new(redis.Storage), new(*postgres.PostgresRepo)), provideRedis,
	provideCacheTTL, redis.New, wire.Bind(new(service.URLRepository), new(*redis.Cache)),
)

// ServiceSet описывает зависимости слоя бизнес-логики
var ServiceSet = wire.NewSet(
	provideAliasGenerator, wire.Bind(new(service.AliasGenerator), new(*random.Generator)), provideServiceConfig, service.New, wire.Bind(new(handlers.URLService), new(*service.Service)),
)

// AuthSet описывает зависимости для аутентификации через sso: gRPC-клиент
// для register/login/refresh/logout и локальный верификатор JWT для
// защищённых маршрутов.
var AuthSet = wire.NewSet(
	provideSSOClientOptions,
	provideSSOClient, wire.Bind(new(handlers.AuthService), new(*ssoclient.Client)), handlers.NewAuth, provideAuthVerifier,
)

var HTTPSet = wire.NewSet(
	provideValidator, handlers.New, httptransport.NewRouter, httptransport.NewServer,
)
