// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"url-shortener/internal/app"
	"url-shortener/internal/config"
	"url-shortener/internal/service/url"
	"url-shortener/internal/storage/postgres"
	"url-shortener/internal/storage/redis"
	"url-shortener/internal/transport/http/handlers"
	"url-shortener/pkg/random"
)

import (
	_ "github.com/golang-migrate/migrate/v4/database/postgres"
	_ "github.com/golang-migrate/migrate/v4/source/file"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*app.App, error) {
	logger := setupLogger(cfg)
	string2 := provideDatabaseURL(cfg)
	postgresRepo, err := postgres.InitPostgres(logger, string2)
	if err != nil {
		return nil, err
	}
	generator := provideAliasGenerator(cfg)
	serviceConfig := provideServiceConfig(cfg)
	serviceService, err := service.New(logger, postgresRepo, generator, serviceConfig)
	if err != nil {
		return nil, err
	}
	validate := provideValidator()
	handler := handlers.New(logger, serviceService, validate)
	router := provideRouter(logger, handler)
	server := provideHTTPServer(cfg, router)
	appApp := app.New(logger, server)
	return appApp, nil
}

// wire.go:

var StorageSet = wire.NewSet(
	provideDatabaseURL, postgres.InitPostgres, wire.Bind(new(service.URLRepository), new(*postgres.PostgresRepo)), provideCacheTTL,
	provideRedis, redis.New,
)

var ServiceSet = wire.NewSet(
	provideAliasGenerator,
	provideServiceConfig, service.New, wire.Bind(
		new(handlers.URLService),
		new(*service.Service),
	), wire.Bind(
		new(service.AliasGenerator),
		new(*random.Generator),
	),
)

var HTTPSet = wire.NewSet(
	provideValidator, handlers.New, provideRouter,
	provideHTTPServer,
)
